spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipe_dev
    username: root
  jpa:
    hibernate:
      ddl_auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
  sql:
    init:
      mode: always
      platform: mysql
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: recipe_database_create.sql